import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from freemail_api.private_beta_evidence import load_private_beta_gate_options_from_manifest  # noqa: E402
from freemail_api.private_beta_gate import PrivateBetaGateOptions, run_private_beta_gate  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser(description="Run FreeMail private-beta readiness gates.")
    parser.add_argument("--manifest", type=Path, help="Private-beta evidence manifest generated by the template tool.")
    parser.add_argument("--domain")
    parser.add_argument("--dns-guidance", type=Path)
    parser.add_argument("--observed-dns", type=Path)
    parser.add_argument("--mail-flow-evidence", type=Path)
    parser.add_argument("--queue-evidence", type=Path)
    parser.add_argument("--mail-core-apply-evidence", type=Path)
    parser.add_argument("--deliverability-evidence", type=Path)
    parser.add_argument("--metadata-backup", type=Path)
    parser.add_argument("--mail-store-backup", type=Path)
    parser.add_argument("--restore-drill-evidence", type=Path)
    parser.add_argument("--acceptance", type=Path)
    parser.add_argument("--skip-dns", action="store_true")
    parser.add_argument("--skip-evidence", action="store_true")
    parser.add_argument("--health-url", default="https://freemail.kuzuryu.ai/health")
    parser.add_argument("--deployment-url", default="https://freemail.kuzuryu.ai/api/v1/deployment")
    parser.add_argument("--metadata-readiness-url", default="https://freemail.kuzuryu.ai/api/v1/metadata/readiness")
    parser.add_argument("--readiness-url", default="https://freemail.kuzuryu.ai/api/v1/mail-core/readiness")
    parser.add_argument(
        "--runtime-commit",
        help="Expected runtime release commit. Defaults to the current Git HEAD when runtime checks are enabled.",
    )
    parser.add_argument("--skip-runtime", action="store_true")
    args = parser.parse_args()

    manifest_options = load_private_beta_gate_options_from_manifest(args.manifest) if args.manifest else None
    result = run_private_beta_gate(
        _options_from_args(args, manifest_options)
    )
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0 if result["passed"] else 2


def _options_from_args(args: argparse.Namespace, manifest: PrivateBetaGateOptions | None) -> PrivateBetaGateOptions:
    return PrivateBetaGateOptions(
        domain=args.domain or _manifest_value(manifest, "domain"),
        dns_guidance=args.dns_guidance or _manifest_value(manifest, "dns_guidance"),
        observed_dns=args.observed_dns or _manifest_value(manifest, "observed_dns"),
        mail_flow_evidence=args.mail_flow_evidence or _manifest_value(manifest, "mail_flow_evidence"),
        queue_evidence=args.queue_evidence or _manifest_value(manifest, "queue_evidence"),
        mail_core_apply_evidence=args.mail_core_apply_evidence or _manifest_value(manifest, "mail_core_apply_evidence"),
        deliverability_evidence=args.deliverability_evidence or _manifest_value(manifest, "deliverability_evidence"),
        metadata_backup=args.metadata_backup or _manifest_value(manifest, "metadata_backup"),
        mail_store_backup=args.mail_store_backup or _manifest_value(manifest, "mail_store_backup"),
        restore_drill_evidence=args.restore_drill_evidence or _manifest_value(manifest, "restore_drill_evidence"),
        acceptance=args.acceptance or _manifest_value(manifest, "acceptance"),
        skip_dns=args.skip_dns,
        skip_evidence=args.skip_evidence,
        health_url=args.health_url,
        deployment_url=args.deployment_url,
        metadata_readiness_url=args.metadata_readiness_url,
        readiness_url=args.readiness_url,
        runtime_commit=args.runtime_commit or _manifest_value(manifest, "runtime_commit"),
        skip_runtime=args.skip_runtime,
    )


def _manifest_value(manifest: PrivateBetaGateOptions | None, field: str):
    return getattr(manifest, field) if manifest else None


if __name__ == "__main__":
    sys.exit(main())
