import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from freemail_api.release_evidence import load_release_packet_status_options_from_manifest  # noqa: E402
from freemail_api.release_packet_status import ReleasePacketStatusOptions, summarize_release_packet  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser(description="Inspect FreeMail release packet artifacts without runtime checks.")
    parser.add_argument("--manifest", type=Path, help="Release evidence manifest generated by the manifest tool.")
    parser.add_argument("--metadata-backup", type=Path)
    parser.add_argument("--mail-store-backup", type=Path)
    parser.add_argument("--restore-drill-evidence", type=Path)
    parser.add_argument("--mobile-release-evidence", type=Path)
    parser.add_argument("--mobile-app-config", type=Path)
    parser.add_argument("--private-beta-evidence", type=Path)
    parser.add_argument("--release-notes", type=Path)
    parser.add_argument("--release-version")
    parser.add_argument("--require-mobile-store-submission", action="store_true")
    args = parser.parse_args()

    manifest_options = load_release_packet_status_options_from_manifest(args.manifest) if args.manifest else None
    result = summarize_release_packet(_options_from_args(args, manifest_options))
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0 if result["ready"] else 1


def _options_from_args(
    args: argparse.Namespace,
    manifest: ReleasePacketStatusOptions | None,
) -> ReleasePacketStatusOptions:
    return ReleasePacketStatusOptions(
        metadata_backup=args.metadata_backup or _manifest_value(manifest, "metadata_backup"),
        mail_store_backup=args.mail_store_backup or _manifest_value(manifest, "mail_store_backup"),
        restore_drill_evidence=args.restore_drill_evidence or _manifest_value(manifest, "restore_drill_evidence"),
        mobile_release_evidence=args.mobile_release_evidence or _manifest_value(manifest, "mobile_release_evidence"),
        mobile_app_config=args.mobile_app_config
        or _manifest_value(manifest, "mobile_app_config")
        or Path("apps/mobile/app.json"),
        private_beta_evidence=args.private_beta_evidence or _manifest_value(manifest, "private_beta_evidence"),
        release_notes=args.release_notes or _manifest_value(manifest, "release_notes"),
        release_version=args.release_version or _manifest_value(manifest, "release_version"),
        require_mobile_store_submission=args.require_mobile_store_submission
        or bool(_manifest_value(manifest, "require_mobile_store_submission")),
    )


def _manifest_value(manifest: ReleasePacketStatusOptions | None, field: str):
    return getattr(manifest, field) if manifest else None


if __name__ == "__main__":
    sys.exit(main())
