import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from freemail_api.release_evidence import load_release_gate_options_from_manifest  # noqa: E402
from freemail_api.release_gate import assert_release_gate, ReleaseGateError, ReleaseGateOptions


def main() -> int:
    parser = argparse.ArgumentParser(description="Run FreeMail local release gates for the current commit.")
    parser.add_argument("--manifest", type=Path, help="Release evidence manifest generated by the manifest tool.")
    parser.add_argument("--repo", default="CYINT/freemail")
    parser.add_argument("--remote", default="origin")
    parser.add_argument("--branch", default="main")
    parser.add_argument("--health-url", default="https://freemail.kuzuryu.ai/health")
    parser.add_argument("--deployment-url", default="https://freemail.kuzuryu.ai/api/v1/deployment")
    parser.add_argument("--metadata-readiness-url", default="https://freemail.kuzuryu.ai/api/v1/metadata/readiness")
    parser.add_argument("--readiness-url", default="https://freemail.kuzuryu.ai/api/v1/mail-core/readiness")
    parser.add_argument("--metadata-backup", type=Path)
    parser.add_argument("--mail-store-backup", type=Path)
    parser.add_argument("--restore-drill-evidence", type=Path)
    parser.add_argument("--mobile-release-evidence", type=Path)
    parser.add_argument("--mobile-app-config", type=Path)
    parser.add_argument("--private-beta-evidence", type=Path)
    parser.add_argument("--release-notes", type=Path)
    parser.add_argument("--release-version")
    parser.add_argument("--skip-github-ci", action="store_true")
    parser.add_argument("--skip-ci-step-provenance", action="store_true")
    parser.add_argument("--skip-codecov-upload", action="store_true")
    parser.add_argument("--skip-repo-secret-scan", action="store_true")
    parser.add_argument("--skip-license-policy-scan", action="store_true")
    parser.add_argument("--skip-backup-evidence", action="store_true")
    parser.add_argument("--skip-mobile-evidence", action="store_true")
    parser.add_argument("--skip-private-beta-evidence", action="store_true")
    parser.add_argument("--require-mobile-store-submission", action="store_true")
    parser.add_argument("--skip-release-notes", action="store_true")
    parser.add_argument("--skip-runtime", action="store_true")
    args = parser.parse_args()

    manifest_options = load_release_gate_options_from_manifest(args.manifest) if args.manifest else None
    options = _options_from_args(args, manifest_options)
    try:
        result = assert_release_gate(options)
    except ReleaseGateError as error:
        print(str(error), file=sys.stderr)
        return 2
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


def _options_from_args(args: argparse.Namespace, manifest: ReleaseGateOptions | None) -> ReleaseGateOptions:
    return ReleaseGateOptions(
        repo=args.repo,
        remote=args.remote,
        branch=args.branch,
        health_url=args.health_url,
        deployment_url=args.deployment_url,
        metadata_readiness_url=args.metadata_readiness_url,
        readiness_url=args.readiness_url,
        metadata_backup=args.metadata_backup or _manifest_value(manifest, "metadata_backup"),
        mail_store_backup=args.mail_store_backup or _manifest_value(manifest, "mail_store_backup"),
        restore_drill_evidence=args.restore_drill_evidence or _manifest_value(manifest, "restore_drill_evidence"),
        mobile_release_evidence=args.mobile_release_evidence or _manifest_value(manifest, "mobile_release_evidence"),
        mobile_app_config=args.mobile_app_config
        or _manifest_value(manifest, "mobile_app_config")
        or Path("apps/mobile/app.json"),
        private_beta_evidence=args.private_beta_evidence or _manifest_value(manifest, "private_beta_evidence"),
        release_notes=args.release_notes or _manifest_value(manifest, "release_notes"),
        release_version=args.release_version or _manifest_value(manifest, "release_version"),
        skip_github_ci=args.skip_github_ci,
        skip_ci_step_provenance=args.skip_ci_step_provenance,
        skip_codecov_upload=args.skip_codecov_upload,
        skip_repo_secret_scan=args.skip_repo_secret_scan,
        skip_license_policy_scan=args.skip_license_policy_scan,
        skip_backup_evidence=args.skip_backup_evidence,
        skip_mobile_evidence=args.skip_mobile_evidence,
        skip_private_beta_evidence=args.skip_private_beta_evidence,
        require_mobile_store_submission=args.require_mobile_store_submission
        or bool(_manifest_value(manifest, "require_mobile_store_submission")),
        skip_release_notes=args.skip_release_notes,
        skip_runtime=args.skip_runtime,
    )


def _manifest_value(manifest: ReleaseGateOptions | None, field: str):
    return getattr(manifest, field) if manifest else None


if __name__ == "__main__":
    sys.exit(main())
